// Curated index of Wikipedia articles for the timeline.
// Only titles + dates live here — every bio, portrait, and summary is fetched
// from the Wikipedia REST API at ingest time. Negative years are BC.

export type PeriodSeed = {
  slug: string;
  name: string;
  start: number;
  end: number;
  wiki: string;
  color: string;
};

export type CivSeed = {
  slug: string;
  name: string;
  period: string;
  start: number;
  end: number;
  displayStart?: number; // optional clamp for timeline placement when the
  displayEnd?: number;   // entity long outlives the period it is filed under
  wiki: string;
};

export type EventSeed = {
  slug: string;
  name: string;
  period: string;
  civ?: string;
  year: number;
  endYear?: number;
  wiki: string;
  onTimeline?: boolean; // false = causal-chain node only, not on the frieze
};

export const PERIODS: PeriodSeed[] = [
  { slug: "ancient-europe", name: "Ancient Europe", start: -3200, end: 476, wiki: "Classical antiquity", color: "#a18d63" },
  { slug: "middle-ages", name: "The Middle Ages", start: 476, end: 1453, wiki: "Middle Ages", color: "#5d6f93" },
  { slug: "renaissance", name: "The Renaissance", start: 1300, end: 1600, wiki: "Renaissance", color: "#a85f48" },
  { slug: "age-of-exploration", name: "The Age of Exploration", start: 1415, end: 1700, wiki: "Age of Discovery", color: "#2f7e74" },
  { slug: "reformation", name: "The Reformation & Religious Wars", start: 1517, end: 1648, wiki: "Reformation", color: "#7c5380" },
  { slug: "enlightenment", name: "The Enlightenment", start: 1637, end: 1789, wiki: "Age of Enlightenment", color: "#c29a45" },
  { slug: "revolutionary-era", name: "The Revolutionary Era", start: 1789, end: 1849, wiki: "Age of Revolution", color: "#b04848" },
  { slug: "industrial-revolution", name: "The Industrial Revolution", start: 1760, end: 1914, wiki: "Industrial Revolution", color: "#6e6862" },
  { slug: "age-of-imperialism", name: "The Age of Imperialism", start: 1869, end: 1914, wiki: "New Imperialism", color: "#8a6a3f" },
  { slug: "world-wars", name: "The World Wars Era", start: 1914, end: 1945, wiki: "World war", color: "#67704a" },
  { slug: "cold-war", name: "The Cold War", start: 1945, end: 1991, wiki: "Cold War", color: "#4a7287" },
  { slug: "contemporary-europe", name: "Contemporary Europe", start: 1991, end: 2026, wiki: "History of the European Union", color: "#4a69b0" },
];

export const CIVILIZATIONS: CivSeed[] = [
  // Ancient Europe
  { slug: "minoans", name: "Minoan Civilization", period: "ancient-europe", start: -3100, end: -1100, wiki: "Minoan civilization" },
  { slug: "ancient-greece", name: "Ancient Greece", period: "ancient-europe", start: -800, end: -146, wiki: "Ancient Greece" },
  { slug: "etruscans", name: "Etruscan Civilization", period: "ancient-europe", start: -900, end: -27, wiki: "Etruscan civilization" },
  { slug: "celts", name: "The Celts", period: "ancient-europe", start: -800, end: 43, wiki: "Celts" },
  { slug: "ancient-rome", name: "Ancient Rome", period: "ancient-europe", start: -753, end: 476, wiki: "Ancient Rome" },
  // Middle Ages
  { slug: "byzantine-empire", name: "Byzantine Empire", period: "middle-ages", start: 330, end: 1453, wiki: "Byzantine Empire" },
  { slug: "francia", name: "The Frankish Kingdoms", period: "middle-ages", start: 481, end: 843, wiki: "Francia" },
  { slug: "vikings", name: "The Vikings", period: "middle-ages", start: 793, end: 1066, wiki: "Vikings" },
  { slug: "kievan-rus", name: "Kievan Rus'", period: "middle-ages", start: 882, end: 1240, wiki: "Kievan Rus'" },
  { slug: "normans", name: "The Normans", period: "middle-ages", start: 911, end: 1204, wiki: "Normans" },
  { slug: "holy-roman-empire", name: "Holy Roman Empire", period: "middle-ages", start: 962, end: 1806, displayEnd: 1453, wiki: "Holy Roman Empire" },
  // Renaissance
  { slug: "republic-of-florence", name: "Republic of Florence", period: "renaissance", start: 1115, end: 1569, displayStart: 1300, wiki: "Republic of Florence" },
  { slug: "house-of-medici", name: "House of Medici", period: "renaissance", start: 1434, end: 1737, displayEnd: 1600, wiki: "House of Medici" },
  { slug: "republic-of-venice", name: "Republic of Venice", period: "renaissance", start: 697, end: 1797, displayStart: 1300, displayEnd: 1600, wiki: "Republic of Venice" },
  { slug: "papal-states", name: "The Papal States", period: "renaissance", start: 754, end: 1870, displayStart: 1300, displayEnd: 1600, wiki: "Papal States" },
  // Age of Exploration
  { slug: "portuguese-empire", name: "Portuguese Empire", period: "age-of-exploration", start: 1415, end: 1999, displayEnd: 1700, wiki: "Portuguese Empire" },
  { slug: "spanish-empire", name: "Spanish Empire", period: "age-of-exploration", start: 1492, end: 1976, displayEnd: 1700, wiki: "Spanish Empire" },
  { slug: "dutch-republic", name: "Dutch Republic", period: "age-of-exploration", start: 1588, end: 1795, displayEnd: 1700, wiki: "Dutch Republic" },
  // Reformation & Religious Wars
  { slug: "habsburg-monarchy", name: "Habsburg Monarchy", period: "reformation", start: 1526, end: 1804, displayEnd: 1648, wiki: "Habsburg monarchy" },
  { slug: "ottoman-empire", name: "Ottoman Empire in Europe", period: "reformation", start: 1299, end: 1922, displayStart: 1453, displayEnd: 1699, wiki: "Ottoman Empire" },
  { slug: "polish-lithuanian-commonwealth", name: "Polish–Lithuanian Commonwealth", period: "reformation", start: 1569, end: 1795, displayEnd: 1648, wiki: "Polish–Lithuanian Commonwealth" },
  { slug: "swedish-empire", name: "Swedish Empire", period: "reformation", start: 1611, end: 1721, displayEnd: 1648, wiki: "Swedish Empire" },
  // Enlightenment
  { slug: "kingdom-of-france", name: "Kingdom of France", period: "enlightenment", start: 987, end: 1792, displayStart: 1643, wiki: "Kingdom of France" },
  { slug: "kingdom-of-great-britain", name: "Kingdom of Great Britain", period: "enlightenment", start: 1707, end: 1800, wiki: "Kingdom of Great Britain" },
  { slug: "kingdom-of-prussia", name: "Kingdom of Prussia", period: "enlightenment", start: 1701, end: 1918, displayEnd: 1789, wiki: "Kingdom of Prussia" },
  { slug: "russian-empire", name: "Russian Empire", period: "enlightenment", start: 1721, end: 1917, displayEnd: 1796, wiki: "Russian Empire" },
  // Revolutionary Era
  { slug: "french-first-republic", name: "French First Republic", period: "revolutionary-era", start: 1792, end: 1804, wiki: "French First Republic" },
  { slug: "first-french-empire", name: "First French Empire", period: "revolutionary-era", start: 1804, end: 1815, wiki: "First French Empire" },
  { slug: "austrian-empire", name: "Austrian Empire", period: "revolutionary-era", start: 1804, end: 1867, displayEnd: 1849, wiki: "Austrian Empire" },
  // Industrial Revolution
  { slug: "united-kingdom-gbi", name: "United Kingdom of Great Britain & Ireland", period: "industrial-revolution", start: 1801, end: 1922, wiki: "United Kingdom of Great Britain and Ireland" },
  { slug: "german-empire", name: "German Empire", period: "industrial-revolution", start: 1871, end: 1918, wiki: "German Empire" },
  { slug: "french-third-republic", name: "French Third Republic", period: "industrial-revolution", start: 1870, end: 1940, displayEnd: 1914, wiki: "French Third Republic" },
  // Age of Imperialism
  { slug: "british-empire", name: "British Empire", period: "age-of-imperialism", start: 1583, end: 1997, displayStart: 1869, displayEnd: 1914, wiki: "British Empire" },
  { slug: "french-colonial-empire", name: "French Colonial Empire", period: "age-of-imperialism", start: 1534, end: 1980, displayStart: 1869, displayEnd: 1914, wiki: "French colonial empire" },
  { slug: "austria-hungary", name: "Austria-Hungary", period: "age-of-imperialism", start: 1867, end: 1918, displayEnd: 1914, wiki: "Austria-Hungary" },
  { slug: "kingdom-of-italy", name: "Kingdom of Italy", period: "age-of-imperialism", start: 1861, end: 1946, displayEnd: 1914, wiki: "Kingdom of Italy" },
  // World Wars Era
  { slug: "weimar-republic", name: "Weimar Republic", period: "world-wars", start: 1918, end: 1933, wiki: "Weimar Republic" },
  { slug: "nazi-germany", name: "Nazi Germany", period: "world-wars", start: 1933, end: 1945, wiki: "Nazi Germany" },
  { slug: "fascist-italy", name: "Fascist Italy", period: "world-wars", start: 1922, end: 1943, wiki: "Fascist Italy" },
  { slug: "second-polish-republic", name: "Second Polish Republic", period: "world-wars", start: 1918, end: 1939, wiki: "Second Polish Republic" },
  // Cold War
  { slug: "soviet-union", name: "Soviet Union", period: "cold-war", start: 1922, end: 1991, wiki: "Soviet Union" },
  { slug: "nato", name: "NATO", period: "cold-war", start: 1949, end: 2026, displayEnd: 1991, wiki: "NATO" },
  { slug: "warsaw-pact", name: "Warsaw Pact", period: "cold-war", start: 1955, end: 1991, wiki: "Warsaw Pact" },
  { slug: "west-germany", name: "West Germany", period: "cold-war", start: 1949, end: 1990, wiki: "West Germany" },
  { slug: "east-germany", name: "East Germany", period: "cold-war", start: 1949, end: 1990, wiki: "East Germany" },
  // Contemporary Europe
  { slug: "european-union", name: "European Union", period: "contemporary-europe", start: 1993, end: 2026, wiki: "European Union" },
  { slug: "russia", name: "Russian Federation", period: "contemporary-europe", start: 1991, end: 2026, wiki: "Russia" },
  { slug: "germany", name: "Reunified Germany", period: "contemporary-europe", start: 1990, end: 2026, wiki: "Germany" },
  { slug: "ukraine", name: "Ukraine", period: "contemporary-europe", start: 1991, end: 2026, wiki: "Ukraine" },
];

export const EVENTS: EventSeed[] = [
  // ───────────── Ancient Europe ─────────────
  { slug: "minoan-eruption", name: "The Minoan Eruption of Thera", period: "ancient-europe", civ: "minoans", year: -1600, wiki: "Minoan eruption" },
  { slug: "trojan-war", name: "The Trojan War", period: "ancient-europe", civ: "ancient-greece", year: -1184, wiki: "Trojan War" },
  { slug: "first-olympic-games", name: "First Olympic Games", period: "ancient-europe", civ: "ancient-greece", year: -776, wiki: "Ancient Olympic Games" },
  { slug: "founding-of-rome", name: "Founding of Rome", period: "ancient-europe", civ: "ancient-rome", year: -753, wiki: "Founding of Rome" },
  { slug: "homeric-epics", name: "Homer's Iliad & Odyssey", period: "ancient-europe", civ: "ancient-greece", year: -750, wiki: "Homer" },
  { slug: "greek-colonisation", name: "Greek Colonisation of the Mediterranean", period: "ancient-europe", civ: "ancient-greece", year: -750, endYear: -550, wiki: "Greek colonisation" },
  { slug: "reforms-of-solon", name: "Reforms of Solon", period: "ancient-europe", civ: "ancient-greece", year: -594, wiki: "Solon" },
  { slug: "roman-republic-founded", name: "Founding of the Roman Republic", period: "ancient-europe", civ: "ancient-rome", year: -509, wiki: "Roman Republic" },
  { slug: "athenian-democracy", name: "Birth of Athenian Democracy", period: "ancient-europe", civ: "ancient-greece", year: -508, wiki: "Athenian democracy" },
  { slug: "ionian-revolt", name: "The Ionian Revolt", period: "ancient-europe", civ: "ancient-greece", year: -499, endYear: -493, wiki: "Ionian Revolt" },
  { slug: "battle-of-marathon", name: "Battle of Marathon", period: "ancient-europe", civ: "ancient-greece", year: -490, wiki: "Battle of Marathon" },
  { slug: "battle-of-thermopylae", name: "Battle of Thermopylae", period: "ancient-europe", civ: "ancient-greece", year: -480, wiki: "Battle of Thermopylae" },
  { slug: "battle-of-salamis", name: "Battle of Salamis", period: "ancient-europe", civ: "ancient-greece", year: -480, wiki: "Battle of Salamis" },
  { slug: "delian-league", name: "The Delian League", period: "ancient-europe", civ: "ancient-greece", year: -478, wiki: "Delian League" },
  { slug: "age-of-pericles", name: "The Age of Pericles", period: "ancient-europe", civ: "ancient-greece", year: -461, endYear: -429, wiki: "Pericles" },
  { slug: "parthenon-built", name: "Building of the Parthenon", period: "ancient-europe", civ: "ancient-greece", year: -447, endYear: -432, wiki: "Parthenon" },
  { slug: "peloponnesian-war", name: "Peloponnesian War", period: "ancient-europe", civ: "ancient-greece", year: -431, endYear: -404, wiki: "Peloponnesian War" },
  { slug: "trial-of-socrates", name: "Trial of Socrates", period: "ancient-europe", civ: "ancient-greece", year: -399, wiki: "Trial of Socrates" },
  { slug: "gauls-sack-rome", name: "Gauls Sack Rome", period: "ancient-europe", civ: "celts", year: -387, wiki: "Battle of the Allia" },
  { slug: "battle-of-chaeronea", name: "Battle of Chaeronea", period: "ancient-europe", civ: "ancient-greece", year: -338, wiki: "Battle of Chaeronea (338 BC)" },
  { slug: "conquests-of-alexander", name: "Conquests of Alexander the Great", period: "ancient-europe", civ: "ancient-greece", year: -334, endYear: -323, wiki: "Wars of Alexander the Great" },
  { slug: "pyrrhic-war", name: "The Pyrrhic War", period: "ancient-europe", civ: "ancient-rome", year: -280, endYear: -275, wiki: "Pyrrhic War" },
  { slug: "punic-wars", name: "The Punic Wars", period: "ancient-europe", civ: "ancient-rome", year: -264, endYear: -146, wiki: "Punic Wars" },
  { slug: "hannibal-crosses-alps", name: "Hannibal Crosses the Alps", period: "ancient-europe", civ: "ancient-rome", year: -218, wiki: "Hannibal's crossing of the Alps" },
  { slug: "reforms-of-the-gracchi", name: "Reforms of the Gracchi", period: "ancient-europe", civ: "ancient-rome", year: -133, endYear: -121, wiki: "Gracchi" },
  { slug: "spartacus-revolt", name: "Spartacus' Slave Revolt", period: "ancient-europe", civ: "ancient-rome", year: -73, endYear: -71, wiki: "Third Servile War" },
  { slug: "gallic-wars", name: "Caesar's Gallic Wars", period: "ancient-europe", civ: "ancient-rome", year: -58, endYear: -50, wiki: "Gallic Wars" },
  { slug: "crossing-the-rubicon", name: "Caesar Crosses the Rubicon", period: "ancient-europe", civ: "ancient-rome", year: -49, wiki: "Crossing the Rubicon" },
  { slug: "assassination-of-caesar", name: "Assassination of Julius Caesar", period: "ancient-europe", civ: "ancient-rome", year: -44, wiki: "Assassination of Julius Caesar" },
  { slug: "battle-of-actium", name: "Battle of Actium", period: "ancient-europe", civ: "ancient-rome", year: -31, wiki: "Battle of Actium" },
  { slug: "pax-romana", name: "Pax Romana", period: "ancient-europe", civ: "ancient-rome", year: -27, endYear: 180, wiki: "Pax Romana" },
  { slug: "teutoburg-forest", name: "Battle of the Teutoburg Forest", period: "ancient-europe", civ: "ancient-rome", year: 9, wiki: "Battle of the Teutoburg Forest" },
  { slug: "great-fire-of-rome", name: "Great Fire of Rome", period: "ancient-europe", civ: "ancient-rome", year: 64, wiki: "Great Fire of Rome" },
  { slug: "eruption-of-vesuvius", name: "Eruption of Vesuvius Buries Pompeii", period: "ancient-europe", civ: "ancient-rome", year: 79, wiki: "Eruption of Mount Vesuvius in 79 AD" },
  { slug: "colosseum-completed", name: "The Colosseum Opens", period: "ancient-europe", civ: "ancient-rome", year: 80, wiki: "Colosseum" },
  { slug: "hadrians-wall", name: "Hadrian's Wall Begun", period: "ancient-europe", civ: "ancient-rome", year: 122, wiki: "Hadrian's Wall" },
  { slug: "crisis-of-third-century", name: "Crisis of the Third Century", period: "ancient-europe", civ: "ancient-rome", year: 235, endYear: 284, wiki: "Crisis of the Third Century" },
  { slug: "edict-of-milan", name: "Edict of Milan", period: "ancient-europe", civ: "ancient-rome", year: 313, wiki: "Edict of Milan" },
  { slug: "founding-of-constantinople", name: "Founding of Constantinople", period: "ancient-europe", civ: "ancient-rome", year: 330, wiki: "Constantinople" },
  { slug: "edict-of-thessalonica", name: "Christianity Becomes the State Religion", period: "ancient-europe", civ: "ancient-rome", year: 380, wiki: "Edict of Thessalonica" },
  { slug: "battle-of-adrianople", name: "Battle of Adrianople", period: "ancient-europe", civ: "ancient-rome", year: 378, wiki: "Battle of Adrianople" },
  { slug: "sack-of-rome-410", name: "Visigoths Sack Rome", period: "ancient-europe", civ: "ancient-rome", year: 410, wiki: "Sack of Rome (410)" },
  { slug: "catalaunian-plains", name: "Attila Halted at the Catalaunian Plains", period: "ancient-europe", civ: "ancient-rome", year: 451, wiki: "Battle of the Catalaunian Plains" },
  { slug: "fall-of-western-rome", name: "Fall of the Western Roman Empire", period: "ancient-europe", civ: "ancient-rome", year: 476, wiki: "Fall of the Western Roman Empire" },

  // ───────────── The Middle Ages ─────────────
  { slug: "baptism-of-clovis", name: "Baptism of Clovis", period: "middle-ages", civ: "francia", year: 496, wiki: "Clovis I" },
  { slug: "spread-of-christianity", name: "The Christianization of Europe", period: "middle-ages", year: 500, endYear: 1000, wiki: "Christianization" },
  { slug: "justinian-code", name: "Justinian's Code of Law", period: "middle-ages", civ: "byzantine-empire", year: 529, wiki: "Corpus Juris Civilis" },
  { slug: "nika-riots", name: "The Nika Riots", period: "middle-ages", civ: "byzantine-empire", year: 532, wiki: "Nika riots" },
  { slug: "hagia-sophia", name: "Hagia Sophia Completed", period: "middle-ages", civ: "byzantine-empire", year: 537, wiki: "Hagia Sophia" },
  { slug: "plague-of-justinian", name: "Plague of Justinian", period: "middle-ages", civ: "byzantine-empire", year: 541, endYear: 549, wiki: "Plague of Justinian" },
  { slug: "umayyad-conquest-hispania", name: "Islamic Conquest of Iberia", period: "middle-ages", year: 711, endYear: 718, wiki: "Umayyad conquest of Hispania" },
  { slug: "reconquista", name: "The Reconquista", period: "middle-ages", year: 722, endYear: 1492, wiki: "Reconquista" },
  { slug: "battle-of-tours", name: "Battle of Tours", period: "middle-ages", civ: "francia", year: 732, wiki: "Battle of Tours" },
  { slug: "raid-on-lindisfarne", name: "Viking Raid on Lindisfarne", period: "middle-ages", civ: "vikings", year: 793, wiki: "Lindisfarne" },
  { slug: "viking-age", name: "The Viking Age", period: "middle-ages", civ: "vikings", year: 793, endYear: 1066, wiki: "Viking Age" },
  { slug: "coronation-of-charlemagne", name: "Coronation of Charlemagne", period: "middle-ages", civ: "francia", year: 800, wiki: "Charlemagne" },
  { slug: "treaty-of-verdun", name: "Treaty of Verdun Divides Francia", period: "middle-ages", civ: "francia", year: 843, wiki: "Treaty of Verdun" },
  { slug: "alfred-the-great", name: "Alfred the Great Defends England", period: "middle-ages", civ: "vikings", year: 871, endYear: 899, wiki: "Alfred the Great" },
  { slug: "cluny-abbey", name: "Founding of Cluny Abbey", period: "middle-ages", year: 910, wiki: "Cluny Abbey" },
  { slug: "otto-i-crowned", name: "Otto I Crowned Emperor", period: "middle-ages", civ: "holy-roman-empire", year: 962, wiki: "Otto the Great" },
  { slug: "christianization-of-rus", name: "Christianization of Kievan Rus'", period: "middle-ages", civ: "kievan-rus", year: 988, wiki: "Christianization of Kievan Rus'" },
  { slug: "east-west-schism", name: "East–West Schism", period: "middle-ages", civ: "byzantine-empire", year: 1054, wiki: "East–West Schism" },
  { slug: "battle-of-hastings", name: "Battle of Hastings", period: "middle-ages", civ: "normans", year: 1066, wiki: "Battle of Hastings" },
  { slug: "investiture-controversy", name: "The Investiture Controversy", period: "middle-ages", civ: "holy-roman-empire", year: 1076, endYear: 1122, wiki: "Investiture Controversy" },
  { slug: "road-to-canossa", name: "Henry IV's Walk to Canossa", period: "middle-ages", civ: "holy-roman-empire", year: 1077, wiki: "Road to Canossa" },
  { slug: "domesday-book", name: "The Domesday Book", period: "middle-ages", civ: "normans", year: 1086, wiki: "Domesday Book" },
  { slug: "first-university", name: "First University Founded at Bologna", period: "middle-ages", year: 1088, wiki: "University of Bologna" },
  { slug: "first-crusade", name: "The First Crusade", period: "middle-ages", year: 1096, endYear: 1099, wiki: "First Crusade" },
  { slug: "concordat-of-worms", name: "Concordat of Worms", period: "middle-ages", civ: "holy-roman-empire", year: 1122, wiki: "Concordat of Worms" },
  { slug: "second-crusade", name: "The Second Crusade", period: "middle-ages", year: 1147, endYear: 1149, wiki: "Second Crusade" },
  { slug: "northern-crusades", name: "The Northern Crusades", period: "middle-ages", year: 1147, endYear: 1410, wiki: "Northern Crusades" },
  { slug: "murder-of-becket", name: "Murder of Thomas Becket", period: "middle-ages", year: 1170, wiki: "Thomas Becket" },
  { slug: "third-crusade", name: "The Third Crusade", period: "middle-ages", year: 1189, endYear: 1192, wiki: "Third Crusade" },
  { slug: "fourth-crusade", name: "The Fourth Crusade", period: "middle-ages", civ: "byzantine-empire", year: 1202, endYear: 1204, wiki: "Fourth Crusade" },
  { slug: "sack-of-constantinople", name: "Sack of Constantinople", period: "middle-ages", civ: "byzantine-empire", year: 1204, wiki: "Sack of Constantinople" },
  { slug: "albigensian-crusade", name: "The Albigensian Crusade", period: "middle-ages", year: 1209, endYear: 1229, wiki: "Albigensian Crusade" },
  { slug: "childrens-crusade", name: "The Children's Crusade", period: "middle-ages", year: 1212, wiki: "Children's Crusade" },
  { slug: "magna-carta", name: "Magna Carta", period: "middle-ages", year: 1215, wiki: "Magna Carta" },
  { slug: "fifth-crusade", name: "The Fifth Crusade", period: "middle-ages", year: 1217, endYear: 1221, wiki: "Fifth Crusade" },
  { slug: "sixth-crusade", name: "The Sixth Crusade", period: "middle-ages", civ: "holy-roman-empire", year: 1228, endYear: 1229, wiki: "Sixth Crusade" },
  { slug: "mongol-invasion", name: "Mongol Invasion of Europe", period: "middle-ages", civ: "kievan-rus", year: 1236, endYear: 1242, wiki: "Mongol invasion of Europe" },
  { slug: "hanseatic-league", name: "Rise of the Hanseatic League", period: "middle-ages", year: 1241, wiki: "Hanseatic League" },
  { slug: "seventh-crusade", name: "The Seventh Crusade", period: "middle-ages", year: 1248, endYear: 1254, wiki: "Seventh Crusade" },
  { slug: "summa-theologica", name: "Aquinas Writes the Summa Theologica", period: "middle-ages", year: 1265, endYear: 1274, wiki: "Summa Theologica" },
  { slug: "eighth-crusade", name: "The Eighth Crusade", period: "middle-ages", year: 1270, wiki: "Eighth Crusade" },
  { slug: "ninth-crusade", name: "The Ninth Crusade", period: "middle-ages", year: 1271, endYear: 1272, wiki: "Lord Edward's Crusade" },
  { slug: "sicilian-vespers", name: "The Sicilian Vespers", period: "middle-ages", year: 1282, wiki: "Sicilian Vespers" },
  { slug: "fall-of-acre", name: "Fall of Acre — End of the Crusader States", period: "middle-ages", year: 1291, wiki: "Siege of Acre (1291)" },
  { slug: "templars-suppressed", name: "Suppression of the Knights Templar", period: "middle-ages", year: 1312, wiki: "Knights Templar" },
  { slug: "great-famine", name: "The Great Famine", period: "middle-ages", year: 1315, endYear: 1317, wiki: "Great Famine of 1315–1317" },
  { slug: "hundred-years-war", name: "Hundred Years' War", period: "middle-ages", year: 1337, endYear: 1453, wiki: "Hundred Years' War" },
  { slug: "black-death", name: "The Black Death", period: "middle-ages", year: 1347, endYear: 1351, wiki: "Black Death" },
  { slug: "golden-bull-1356", name: "The Golden Bull of 1356", period: "middle-ages", civ: "holy-roman-empire", year: 1356, wiki: "Golden Bull of 1356" },
  { slug: "western-schism", name: "The Western Schism", period: "middle-ages", year: 1378, endYear: 1417, wiki: "Western Schism" },
  { slug: "battle-of-grunwald", name: "Battle of Grunwald", period: "middle-ages", year: 1410, wiki: "Battle of Grunwald" },
  { slug: "council-of-constance", name: "Council of Constance", period: "middle-ages", year: 1414, endYear: 1418, wiki: "Council of Constance" },
  { slug: "execution-of-jan-hus", name: "Execution of Jan Hus", period: "middle-ages", year: 1415, wiki: "Jan Hus" },
  { slug: "battle-of-agincourt", name: "Battle of Agincourt", period: "middle-ages", year: 1415, wiki: "Battle of Agincourt" },
  { slug: "joan-of-arc", name: "Joan of Arc Lifts the Siege of Orléans", period: "middle-ages", year: 1429, wiki: "Joan of Arc" },
  { slug: "fall-of-constantinople", name: "Fall of Constantinople", period: "middle-ages", civ: "byzantine-empire", year: 1453, wiki: "Fall of Constantinople" },

  // ───────────── The Renaissance ─────────────
  { slug: "divine-comedy", name: "Dante's Divine Comedy", period: "renaissance", year: 1320, wiki: "Divine Comedy" },
  { slug: "petrarch-laureate", name: "Petrarch Crowned Poet Laureate", period: "renaissance", year: 1341, wiki: "Petrarch" },
  { slug: "the-decameron", name: "Boccaccio's Decameron", period: "renaissance", civ: "republic-of-florence", year: 1353, wiki: "The Decameron" },
  { slug: "brunelleschi-dome", name: "Brunelleschi's Dome Completed", period: "renaissance", civ: "republic-of-florence", year: 1436, wiki: "Florence Cathedral" },
  { slug: "printing-press", name: "Gutenberg's Printing Press", period: "renaissance", year: 1440, wiki: "Printing press" },
  { slug: "gutenberg-bible", name: "The Gutenberg Bible", period: "renaissance", year: 1455, wiki: "Gutenberg Bible" },
  { slug: "birth-of-venus", name: "Botticelli's Birth of Venus", period: "renaissance", civ: "republic-of-florence", year: 1485, wiki: "The Birth of Venus" },
  { slug: "italian-wars", name: "The Italian Wars", period: "renaissance", year: 1494, endYear: 1559, wiki: "Italian Wars" },
  { slug: "bonfire-of-the-vanities", name: "Savonarola's Bonfire of the Vanities", period: "renaissance", civ: "republic-of-florence", year: 1497, wiki: "Bonfire of the vanities" },
  { slug: "the-last-supper", name: "Leonardo's Last Supper", period: "renaissance", year: 1498, wiki: "The Last Supper (Leonardo)" },
  { slug: "mona-lisa", name: "Leonardo Paints the Mona Lisa", period: "renaissance", civ: "republic-of-florence", year: 1503, wiki: "Mona Lisa" },
  { slug: "david-michelangelo", name: "Michelangelo's David", period: "renaissance", civ: "republic-of-florence", year: 1504, wiki: "David (Michelangelo)" },
  { slug: "school-of-athens", name: "Raphael's School of Athens", period: "renaissance", civ: "papal-states", year: 1511, wiki: "The School of Athens" },
  { slug: "praise-of-folly", name: "Erasmus' In Praise of Folly", period: "renaissance", year: 1511, wiki: "In Praise of Folly" },
  { slug: "sistine-chapel-ceiling", name: "Sistine Chapel Ceiling", period: "renaissance", civ: "papal-states", year: 1512, wiki: "Sistine Chapel ceiling" },
  { slug: "utopia-more", name: "Thomas More's Utopia", period: "renaissance", year: 1516, wiki: "Utopia (book)" },
  { slug: "sack-of-rome-1527", name: "Sack of Rome", period: "renaissance", civ: "papal-states", year: 1527, wiki: "Sack of Rome (1527)" },
  { slug: "book-of-the-courtier", name: "Castiglione's Book of the Courtier", period: "renaissance", year: 1528, wiki: "The Book of the Courtier" },
  { slug: "the-prince", name: "Machiavelli's The Prince", period: "renaissance", civ: "republic-of-florence", year: 1532, wiki: "The Prince" },
  { slug: "copernican-heliocentrism", name: "Copernicus' Heliocentric Model", period: "renaissance", year: 1543, wiki: "Nicolaus Copernicus" },
  { slug: "vesalius-fabrica", name: "Vesalius Maps the Human Body", period: "renaissance", year: 1543, wiki: "De Humani Corporis Fabrica" },
  { slug: "tycho-supernova", name: "Tycho's Supernova Challenges the Heavens", period: "renaissance", year: 1572, wiki: "SN 1572" },

  // ───────────── The Age of Exploration ─────────────
  { slug: "conquest-of-ceuta", name: "Conquest of Ceuta", period: "age-of-exploration", civ: "portuguese-empire", year: 1415, wiki: "Conquest of Ceuta" },
  { slug: "henry-the-navigator", name: "Henry the Navigator's Voyages Begin", period: "age-of-exploration", civ: "portuguese-empire", year: 1418, wiki: "Prince Henry the Navigator" },
  { slug: "rounding-cape-bojador", name: "Gil Eanes Rounds Cape Bojador", period: "age-of-exploration", civ: "portuguese-empire", year: 1434, wiki: "Gil Eanes" },
  { slug: "dias-rounds-the-cape", name: "Dias Rounds the Cape of Good Hope", period: "age-of-exploration", civ: "portuguese-empire", year: 1488, wiki: "Bartolomeu Dias" },
  { slug: "voyages-of-columbus", name: "Columbus Reaches the Americas", period: "age-of-exploration", civ: "spanish-empire", year: 1492, wiki: "Voyages of Christopher Columbus" },
  { slug: "treaty-of-tordesillas", name: "Treaty of Tordesillas", period: "age-of-exploration", year: 1494, wiki: "Treaty of Tordesillas" },
  { slug: "cabot-reaches-newfoundland", name: "John Cabot Reaches Newfoundland", period: "age-of-exploration", year: 1497, wiki: "John Cabot" },
  { slug: "vasco-da-gama-india", name: "Vasco da Gama Reaches India", period: "age-of-exploration", civ: "portuguese-empire", year: 1498, wiki: "Vasco da Gama" },
  { slug: "cabral-reaches-brazil", name: "Cabral Claims Brazil", period: "age-of-exploration", civ: "portuguese-empire", year: 1500, wiki: "Pedro Álvares Cabral" },
  { slug: "columbian-exchange", name: "The Columbian Exchange", period: "age-of-exploration", year: 1500, endYear: 1600, wiki: "Columbian exchange" },
  { slug: "magellan-circumnavigation", name: "First Circumnavigation of the Globe", period: "age-of-exploration", civ: "spanish-empire", year: 1519, endYear: 1522, wiki: "Magellan expedition" },
  { slug: "conquest-of-the-aztecs", name: "Conquest of the Aztec Empire", period: "age-of-exploration", civ: "spanish-empire", year: 1519, endYear: 1521, wiki: "Spanish conquest of the Aztec Empire" },
  { slug: "conquest-of-the-inca", name: "Conquest of the Inca Empire", period: "age-of-exploration", civ: "spanish-empire", year: 1532, endYear: 1533, wiki: "Spanish conquest of the Inca Empire" },
  { slug: "cartier-canada", name: "Cartier Explores the St. Lawrence", period: "age-of-exploration", civ: "kingdom-of-france", year: 1534, wiki: "Jacques Cartier" },
  { slug: "silver-of-potosi", name: "The Silver Mountain of Potosí", period: "age-of-exploration", civ: "spanish-empire", year: 1545, wiki: "Potosí" },
  { slug: "spanish-armada", name: "The Spanish Armada", period: "age-of-exploration", civ: "spanish-empire", year: 1588, wiki: "Spanish Armada" },
  { slug: "dutch-east-india-company", name: "Dutch East India Company Founded", period: "age-of-exploration", civ: "dutch-republic", year: 1602, wiki: "Dutch East India Company" },
  { slug: "jamestown-founded", name: "Jamestown — First English Colony", period: "age-of-exploration", year: 1607, wiki: "Jamestown, Virginia" },
  { slug: "hudson-voyages", name: "Hudson Searches for the Northwest Passage", period: "age-of-exploration", civ: "dutch-republic", year: 1609, wiki: "Henry Hudson" },
  { slug: "mayflower-voyage", name: "Voyage of the Mayflower", period: "age-of-exploration", year: 1620, wiki: "Mayflower" },
  { slug: "tasman-voyages", name: "Tasman Charts the South Seas", period: "age-of-exploration", civ: "dutch-republic", year: 1642, endYear: 1644, wiki: "Abel Tasman" },

  // ───────────── The Reformation & Religious Wars ─────────────
  { slug: "ninety-five-theses", name: "Luther's Ninety-five Theses", period: "reformation", year: 1517, wiki: "Ninety-five Theses" },
  { slug: "diet-of-worms", name: "Diet of Worms", period: "reformation", year: 1521, wiki: "Diet of Worms" },
  { slug: "german-peasants-war", name: "The German Peasants' War", period: "reformation", year: 1524, endYear: 1525, wiki: "German Peasants' War" },
  { slug: "luther-bible", name: "Luther's German Bible", period: "reformation", year: 1534, wiki: "Luther Bible" },
  { slug: "english-reformation", name: "The English Reformation", period: "reformation", year: 1534, wiki: "English Reformation" },
  { slug: "munster-rebellion", name: "The Anabaptist Kingdom of Münster", period: "reformation", year: 1534, endYear: 1535, wiki: "Münster rebellion" },
  { slug: "calvin-in-geneva", name: "Calvin's Geneva", period: "reformation", year: 1536, wiki: "John Calvin" },
  { slug: "jesuits-founded", name: "Founding of the Jesuits", period: "reformation", year: 1540, wiki: "Society of Jesus" },
  { slug: "council-of-trent", name: "Council of Trent", period: "reformation", year: 1545, endYear: 1563, wiki: "Council of Trent" },
  { slug: "peace-of-augsburg", name: "Peace of Augsburg", period: "reformation", civ: "habsburg-monarchy", year: 1555, wiki: "Peace of Augsburg" },
  { slug: "elizabethan-settlement", name: "The Elizabethan Religious Settlement", period: "reformation", year: 1559, wiki: "Elizabethan Religious Settlement" },
  { slug: "french-wars-of-religion", name: "French Wars of Religion", period: "reformation", year: 1562, endYear: 1598, wiki: "French Wars of Religion" },
  { slug: "dutch-revolt", name: "The Dutch Revolt", period: "reformation", civ: "dutch-republic", year: 1568, endYear: 1648, wiki: "Dutch Revolt" },
  { slug: "battle-of-lepanto", name: "Battle of Lepanto", period: "reformation", civ: "ottoman-empire", year: 1571, wiki: "Battle of Lepanto" },
  { slug: "st-bartholomews-massacre", name: "St. Bartholomew's Day Massacre", period: "reformation", year: 1572, wiki: "St. Bartholomew's Day massacre" },
  { slug: "union-of-utrecht", name: "Union of Utrecht", period: "reformation", civ: "dutch-republic", year: 1579, wiki: "Union of Utrecht" },
  { slug: "gregorian-calendar", name: "The Gregorian Calendar Reform", period: "reformation", year: 1582, wiki: "Gregorian calendar" },
  { slug: "edict-of-nantes", name: "Edict of Nantes", period: "reformation", year: 1598, wiki: "Edict of Nantes" },
  { slug: "gunpowder-plot", name: "The Gunpowder Plot", period: "reformation", year: 1605, wiki: "Gunpowder Plot" },
  { slug: "defenestration-of-prague", name: "Defenestration of Prague", period: "reformation", civ: "habsburg-monarchy", year: 1618, wiki: "Defenestrations of Prague" },
  { slug: "thirty-years-war", name: "Thirty Years' War", period: "reformation", civ: "habsburg-monarchy", year: 1618, endYear: 1648, wiki: "Thirty Years' War" },
  { slug: "battle-of-white-mountain", name: "Battle of White Mountain", period: "reformation", civ: "habsburg-monarchy", year: 1620, wiki: "Battle of White Mountain" },
  { slug: "sack-of-magdeburg", name: "Sack of Magdeburg", period: "reformation", year: 1631, wiki: "Sack of Magdeburg" },
  { slug: "battle-of-lutzen", name: "Battle of Lützen", period: "reformation", civ: "swedish-empire", year: 1632, wiki: "Battle of Lützen (1632)" },
  { slug: "peace-of-westphalia", name: "Peace of Westphalia", period: "reformation", year: 1648, wiki: "Peace of Westphalia" },

  // ───────────── The Enlightenment ─────────────
  { slug: "discourse-on-method", name: "Descartes' Discourse on the Method", period: "enlightenment", year: 1637, wiki: "Discourse on the Method" },
  { slug: "english-civil-war", name: "The English Civil War", period: "enlightenment", year: 1642, endYear: 1651, wiki: "English Civil War" },
  { slug: "execution-of-charles-i", name: "Execution of Charles I", period: "enlightenment", year: 1649, wiki: "Execution of Charles I" },
  { slug: "leviathan-hobbes", name: "Hobbes' Leviathan", period: "enlightenment", year: 1651, wiki: "Leviathan (Hobbes book)" },
  { slug: "royal-society", name: "Founding of the Royal Society", period: "enlightenment", year: 1660, wiki: "Royal Society" },
  { slug: "great-plague-of-london", name: "Great Plague of London", period: "enlightenment", year: 1665, wiki: "Great Plague of London" },
  { slug: "great-fire-of-london", name: "Great Fire of London", period: "enlightenment", year: 1666, wiki: "Great Fire of London" },
  { slug: "siege-of-vienna-1683", name: "Ottoman Siege of Vienna Repelled", period: "enlightenment", civ: "habsburg-monarchy", year: 1683, wiki: "Battle of Vienna" },
  { slug: "newtons-principia", name: "Newton's Principia", period: "enlightenment", civ: "kingdom-of-great-britain", year: 1687, wiki: "Philosophiæ Naturalis Principia Mathematica" },
  { slug: "glorious-revolution", name: "The Glorious Revolution", period: "enlightenment", civ: "kingdom-of-great-britain", year: 1688, wiki: "Glorious Revolution" },
  { slug: "bill-of-rights-1689", name: "The English Bill of Rights", period: "enlightenment", civ: "kingdom-of-great-britain", year: 1689, wiki: "Bill of Rights 1689" },
  { slug: "two-treatises", name: "Locke's Two Treatises of Government", period: "enlightenment", year: 1689, wiki: "Two Treatises of Government" },
  { slug: "great-northern-war", name: "The Great Northern War", period: "enlightenment", civ: "russian-empire", year: 1700, endYear: 1721, wiki: "Great Northern War" },
  { slug: "war-of-spanish-succession", name: "War of the Spanish Succession", period: "enlightenment", year: 1701, endYear: 1714, wiki: "War of the Spanish Succession" },
  { slug: "founding-of-st-petersburg", name: "Founding of Saint Petersburg", period: "enlightenment", civ: "russian-empire", year: 1703, wiki: "Saint Petersburg" },
  { slug: "acts-of-union-1707", name: "Acts of Union Create Great Britain", period: "enlightenment", civ: "kingdom-of-great-britain", year: 1707, wiki: "Acts of Union 1707" },
  { slug: "peace-of-utrecht", name: "Peace of Utrecht", period: "enlightenment", year: 1713, wiki: "Peace of Utrecht" },
  { slug: "war-of-austrian-succession", name: "War of the Austrian Succession", period: "enlightenment", civ: "kingdom-of-prussia", year: 1740, endYear: 1748, wiki: "War of the Austrian Succession" },
  { slug: "encyclopedie", name: "Diderot's Encyclopédie", period: "enlightenment", civ: "kingdom-of-france", year: 1751, wiki: "Encyclopédie" },
  { slug: "lisbon-earthquake", name: "The Great Lisbon Earthquake", period: "enlightenment", year: 1755, wiki: "1755 Lisbon earthquake" },
  { slug: "seven-years-war", name: "The Seven Years' War", period: "enlightenment", civ: "kingdom-of-prussia", year: 1756, endYear: 1763, wiki: "Seven Years' War" },
  { slug: "candide", name: "Voltaire's Candide", period: "enlightenment", civ: "kingdom-of-france", year: 1759, wiki: "Candide" },
  { slug: "social-contract", name: "Rousseau's Social Contract", period: "enlightenment", civ: "kingdom-of-france", year: 1762, wiki: "The Social Contract" },
  { slug: "partitions-of-poland", name: "The Partitions of Poland", period: "enlightenment", civ: "polish-lithuanian-commonwealth", year: 1772, endYear: 1795, wiki: "Partitions of Poland" },
  { slug: "wealth-of-nations", name: "Smith's Wealth of Nations", period: "enlightenment", civ: "kingdom-of-great-britain", year: 1776, wiki: "The Wealth of Nations" },
  { slug: "first-balloon-flight", name: "First Manned Balloon Flight", period: "enlightenment", civ: "kingdom-of-france", year: 1783, wiki: "Montgolfier brothers" },

  // ───────────── The Revolutionary Era ─────────────
  { slug: "estates-general-1789", name: "The Estates General Convene", period: "revolutionary-era", year: 1789, wiki: "Estates General of 1789" },
  { slug: "storming-of-the-bastille", name: "Storming of the Bastille", period: "revolutionary-era", year: 1789, wiki: "Storming of the Bastille" },
  { slug: "rights-of-man", name: "Declaration of the Rights of Man", period: "revolutionary-era", year: 1789, wiki: "Declaration of the Rights of Man and of the Citizen" },
  { slug: "womens-march-versailles", name: "Women's March on Versailles", period: "revolutionary-era", year: 1789, wiki: "Women's March on Versailles" },
  { slug: "flight-to-varennes", name: "The Flight to Varennes", period: "revolutionary-era", year: 1791, wiki: "Flight to Varennes" },
  { slug: "execution-of-louis-xvi", name: "Execution of Louis XVI", period: "revolutionary-era", civ: "french-first-republic", year: 1793, wiki: "Execution of Louis XVI" },
  { slug: "reign-of-terror", name: "The Reign of Terror", period: "revolutionary-era", civ: "french-first-republic", year: 1793, endYear: 1794, wiki: "Reign of Terror" },
  { slug: "thermidorian-reaction", name: "The Thermidorian Reaction", period: "revolutionary-era", civ: "french-first-republic", year: 1794, wiki: "Thermidorian Reaction" },
  { slug: "coup-of-18-brumaire", name: "Napoleon's Coup of 18 Brumaire", period: "revolutionary-era", civ: "french-first-republic", year: 1799, wiki: "Coup of 18 Brumaire" },
  { slug: "napoleonic-wars", name: "The Napoleonic Wars", period: "revolutionary-era", civ: "first-french-empire", year: 1803, endYear: 1815, wiki: "Napoleonic Wars" },
  { slug: "napoleonic-code", name: "The Napoleonic Code", period: "revolutionary-era", civ: "first-french-empire", year: 1804, wiki: "Napoleonic Code" },
  { slug: "coronation-of-napoleon", name: "Coronation of Napoleon", period: "revolutionary-era", civ: "first-french-empire", year: 1804, wiki: "Coronation of Napoleon" },
  { slug: "battle-of-trafalgar", name: "Battle of Trafalgar", period: "revolutionary-era", civ: "first-french-empire", year: 1805, wiki: "Battle of Trafalgar" },
  { slug: "battle-of-austerlitz", name: "Battle of Austerlitz", period: "revolutionary-era", civ: "first-french-empire", year: 1805, wiki: "Battle of Austerlitz" },
  { slug: "continental-system", name: "The Continental System", period: "revolutionary-era", civ: "first-french-empire", year: 1806, wiki: "Continental System" },
  { slug: "peninsular-war", name: "The Peninsular War", period: "revolutionary-era", civ: "first-french-empire", year: 1808, endYear: 1814, wiki: "Peninsular War" },
  { slug: "invasion-of-russia-1812", name: "Napoleon's Invasion of Russia", period: "revolutionary-era", civ: "first-french-empire", year: 1812, wiki: "French invasion of Russia" },
  { slug: "battle-of-leipzig", name: "Battle of Leipzig", period: "revolutionary-era", civ: "first-french-empire", year: 1813, wiki: "Battle of Leipzig" },
  { slug: "congress-of-vienna", name: "Congress of Vienna", period: "revolutionary-era", civ: "austrian-empire", year: 1814, endYear: 1815, wiki: "Congress of Vienna" },
  { slug: "battle-of-waterloo", name: "Battle of Waterloo", period: "revolutionary-era", civ: "first-french-empire", year: 1815, wiki: "Battle of Waterloo" },
  { slug: "carlsbad-decrees", name: "The Carlsbad Decrees", period: "revolutionary-era", civ: "austrian-empire", year: 1819, wiki: "Carlsbad Decrees" },
  { slug: "greek-independence", name: "Greek War of Independence", period: "revolutionary-era", year: 1821, endYear: 1829, wiki: "Greek War of Independence" },
  { slug: "decembrist-revolt", name: "The Decembrist Revolt", period: "revolutionary-era", civ: "russian-empire", year: 1825, wiki: "Decembrist revolt" },
  { slug: "july-revolution", name: "The July Revolution", period: "revolutionary-era", year: 1830, wiki: "July Revolution" },
  { slug: "belgian-revolution", name: "The Belgian Revolution", period: "revolutionary-era", year: 1830, endYear: 1831, wiki: "Belgian Revolution" },
  { slug: "revolutions-of-1848", name: "Revolutions of 1848", period: "revolutionary-era", year: 1848, wiki: "Revolutions of 1848" },

  // ───────────── The Industrial Revolution ─────────────
  { slug: "spinning-jenny", name: "The Spinning Jenny", period: "industrial-revolution", year: 1764, wiki: "Spinning jenny" },
  { slug: "watt-steam-engine", name: "Watt's Steam Engine", period: "industrial-revolution", year: 1776, wiki: "Watt steam engine" },
  { slug: "iron-bridge", name: "The First Iron Bridge", period: "industrial-revolution", year: 1779, wiki: "The Iron Bridge" },
  { slug: "power-loom", name: "Cartwright's Power Loom", period: "industrial-revolution", year: 1785, wiki: "Power loom" },
  { slug: "first-vaccine", name: "Jenner's Smallpox Vaccine", period: "industrial-revolution", year: 1796, wiki: "Edward Jenner" },
  { slug: "first-locomotive", name: "Trevithick's First Locomotive", period: "industrial-revolution", year: 1804, wiki: "Richard Trevithick" },
  { slug: "luddite-uprisings", name: "The Luddite Uprisings", period: "industrial-revolution", civ: "united-kingdom-gbi", year: 1811, endYear: 1816, wiki: "Luddite" },
  { slug: "first-passenger-railway", name: "First Public Railway", period: "industrial-revolution", civ: "united-kingdom-gbi", year: 1825, wiki: "Stockton and Darlington Railway" },
  { slug: "stephensons-rocket", name: "Stephenson's Rocket", period: "industrial-revolution", civ: "united-kingdom-gbi", year: 1829, wiki: "Stephenson's Rocket" },
  { slug: "electrical-telegraph", name: "The Electrical Telegraph", period: "industrial-revolution", year: 1837, wiki: "Electrical telegraph" },
  { slug: "irish-great-famine", name: "The Great Irish Famine", period: "industrial-revolution", civ: "united-kingdom-gbi", year: 1845, endYear: 1852, wiki: "Great Famine (Ireland)" },
  { slug: "communist-manifesto", name: "The Communist Manifesto", period: "industrial-revolution", year: 1848, wiki: "The Communist Manifesto" },
  { slug: "great-exhibition", name: "The Great Exhibition", period: "industrial-revolution", civ: "united-kingdom-gbi", year: 1851, wiki: "Great Exhibition" },
  { slug: "crimean-war", name: "The Crimean War", period: "industrial-revolution", civ: "russian-empire", year: 1853, endYear: 1856, wiki: "Crimean War" },
  { slug: "bessemer-process", name: "The Bessemer Steel Process", period: "industrial-revolution", year: 1856, wiki: "Bessemer process" },
  { slug: "origin-of-species", name: "Darwin's Origin of Species", period: "industrial-revolution", civ: "united-kingdom-gbi", year: 1859, wiki: "On the Origin of Species" },
  { slug: "unification-of-italy", name: "Unification of Italy", period: "industrial-revolution", civ: "kingdom-of-italy", year: 1861, wiki: "Italian unification" },
  { slug: "london-underground", name: "First Underground Railway", period: "industrial-revolution", civ: "united-kingdom-gbi", year: 1863, wiki: "London Underground" },
  { slug: "first-international", name: "The First International", period: "industrial-revolution", year: 1864, wiki: "International Workingmen's Association" },
  { slug: "pasteurization", name: "Pasteur's Germ Theory", period: "industrial-revolution", civ: "french-third-republic", year: 1864, wiki: "Louis Pasteur" },
  { slug: "franco-prussian-war", name: "Franco-Prussian War", period: "industrial-revolution", civ: "german-empire", year: 1870, endYear: 1871, wiki: "Franco-Prussian War" },
  { slug: "unification-of-germany", name: "Unification of Germany", period: "industrial-revolution", civ: "german-empire", year: 1871, wiki: "Unification of Germany" },
  { slug: "paris-commune", name: "The Paris Commune", period: "industrial-revolution", civ: "french-third-republic", year: 1871, wiki: "Paris Commune" },
  { slug: "second-industrial-revolution", name: "Second Industrial Revolution", period: "industrial-revolution", year: 1870, endYear: 1914, wiki: "Second Industrial Revolution" },
  { slug: "first-automobile", name: "Benz Builds the First Automobile", period: "industrial-revolution", civ: "german-empire", year: 1885, wiki: "Carl Benz" },
  { slug: "eiffel-tower", name: "The Eiffel Tower Rises", period: "industrial-revolution", civ: "french-third-republic", year: 1889, wiki: "Eiffel Tower" },
  { slug: "birth-of-radio", name: "Marconi's Wireless Telegraphy", period: "industrial-revolution", civ: "kingdom-of-italy", year: 1895, wiki: "Guglielmo Marconi" },

  // ───────────── The Age of Imperialism ─────────────
  { slug: "suez-canal", name: "Opening of the Suez Canal", period: "age-of-imperialism", year: 1869, wiki: "Suez Canal" },
  { slug: "congress-of-berlin", name: "Congress of Berlin", period: "age-of-imperialism", year: 1878, wiki: "Congress of Berlin" },
  { slug: "scramble-for-africa", name: "The Scramble for Africa", period: "age-of-imperialism", year: 1881, endYear: 1914, wiki: "Scramble for Africa" },
  { slug: "triple-alliance-1882", name: "The Triple Alliance", period: "age-of-imperialism", civ: "austria-hungary", year: 1882, wiki: "Triple Alliance (1882)" },
  { slug: "berlin-conference", name: "Berlin Conference", period: "age-of-imperialism", year: 1884, endYear: 1885, wiki: "Berlin Conference" },
  { slug: "dreyfus-affair", name: "The Dreyfus Affair", period: "age-of-imperialism", civ: "french-colonial-empire", year: 1894, wiki: "Dreyfus affair" },
  { slug: "fashoda-incident", name: "The Fashoda Incident", period: "age-of-imperialism", civ: "french-colonial-empire", year: 1898, wiki: "Fashoda Incident" },
  { slug: "spanish-american-war", name: "Spain Loses Its Empire", period: "age-of-imperialism", year: 1898, wiki: "Spanish–American War" },
  { slug: "second-boer-war", name: "Second Boer War", period: "age-of-imperialism", civ: "british-empire", year: 1899, endYear: 1902, wiki: "Second Boer War" },
  { slug: "entente-cordiale", name: "Entente Cordiale", period: "age-of-imperialism", year: 1904, wiki: "Entente Cordiale" },
  { slug: "russo-japanese-war", name: "Russo-Japanese War", period: "age-of-imperialism", civ: "russian-empire", year: 1904, endYear: 1905, wiki: "Russo-Japanese War" },
  { slug: "russian-revolution-1905", name: "The Russian Revolution of 1905", period: "age-of-imperialism", civ: "russian-empire", year: 1905, wiki: "Russian Revolution of 1905" },
  { slug: "first-moroccan-crisis", name: "First Moroccan Crisis", period: "age-of-imperialism", year: 1905, wiki: "First Moroccan Crisis" },
  { slug: "triple-entente", name: "The Triple Entente", period: "age-of-imperialism", year: 1907, wiki: "Triple Entente" },
  { slug: "bosnian-crisis", name: "The Bosnian Crisis", period: "age-of-imperialism", civ: "austria-hungary", year: 1908, wiki: "Bosnian Crisis" },
  { slug: "agadir-crisis", name: "The Agadir Crisis", period: "age-of-imperialism", year: 1911, wiki: "Agadir Crisis" },
  { slug: "italo-turkish-war", name: "Italo-Turkish War", period: "age-of-imperialism", civ: "kingdom-of-italy", year: 1911, endYear: 1912, wiki: "Italo-Turkish War" },
  { slug: "balkan-wars", name: "The Balkan Wars", period: "age-of-imperialism", year: 1912, endYear: 1913, wiki: "Balkan Wars" },

  // ───────────── The World Wars Era ─────────────
  { slug: "franz-ferdinand", name: "Assassination of Franz Ferdinand", period: "world-wars", civ: "austria-hungary", year: 1914, wiki: "Assassination of Archduke Franz Ferdinand" },
  { slug: "july-crisis", name: "The July Crisis", period: "world-wars", year: 1914, wiki: "July Crisis" },
  { slug: "first-battle-of-the-marne", name: "First Battle of the Marne", period: "world-wars", year: 1914, wiki: "First Battle of the Marne" },
  { slug: "christmas-truce", name: "The Christmas Truce", period: "world-wars", year: 1914, wiki: "Christmas truce" },
  { slug: "gallipoli-campaign", name: "The Gallipoli Campaign", period: "world-wars", year: 1915, endYear: 1916, wiki: "Gallipoli campaign" },
  { slug: "battle-of-verdun", name: "Battle of Verdun", period: "world-wars", year: 1916, wiki: "Battle of Verdun" },
  { slug: "battle-of-the-somme", name: "Battle of the Somme", period: "world-wars", year: 1916, wiki: "Battle of the Somme" },
  { slug: "battle-of-jutland", name: "Battle of Jutland", period: "world-wars", year: 1916, wiki: "Battle of Jutland" },
  { slug: "easter-rising", name: "The Easter Rising", period: "world-wars", year: 1916, wiki: "Easter Rising" },
  { slug: "february-revolution", name: "The February Revolution", period: "world-wars", year: 1917, wiki: "February Revolution" },
  { slug: "russian-revolution", name: "The Russian Revolution", period: "world-wars", year: 1917, wiki: "Russian Revolution" },
  { slug: "october-revolution", name: "The October Revolution", period: "world-wars", year: 1917, wiki: "October Revolution" },
  { slug: "armistice-1918", name: "Armistice of 11 November 1918", period: "world-wars", year: 1918, wiki: "Armistice of 11 November 1918" },
  { slug: "spanish-flu", name: "The Spanish Flu Pandemic", period: "world-wars", year: 1918, endYear: 1920, wiki: "Spanish flu" },
  { slug: "treaty-of-versailles", name: "Treaty of Versailles", period: "world-wars", civ: "weimar-republic", year: 1919, wiki: "Treaty of Versailles" },
  { slug: "irish-war-of-independence", name: "Irish War of Independence", period: "world-wars", year: 1919, endYear: 1921, wiki: "Irish War of Independence" },
  { slug: "march-on-rome", name: "Mussolini's March on Rome", period: "world-wars", civ: "fascist-italy", year: 1922, wiki: "March on Rome" },
  { slug: "weimar-hyperinflation", name: "Weimar Hyperinflation", period: "world-wars", civ: "weimar-republic", year: 1923, wiki: "Hyperinflation in the Weimar Republic" },
  { slug: "beer-hall-putsch", name: "The Beer Hall Putsch", period: "world-wars", civ: "weimar-republic", year: 1923, wiki: "Beer Hall Putsch" },
  { slug: "locarno-treaties", name: "The Locarno Treaties", period: "world-wars", civ: "weimar-republic", year: 1925, wiki: "Locarno Treaties" },
  { slug: "great-depression", name: "The Great Depression", period: "world-wars", year: 1929, wiki: "Great Depression" },
  { slug: "hitler-rise-to-power", name: "Hitler Seizes Power", period: "world-wars", civ: "nazi-germany", year: 1933, wiki: "Adolf Hitler's rise to power" },
  { slug: "reichstag-fire", name: "The Reichstag Fire", period: "world-wars", civ: "nazi-germany", year: 1933, wiki: "Reichstag fire" },
  { slug: "night-of-the-long-knives", name: "Night of the Long Knives", period: "world-wars", civ: "nazi-germany", year: 1934, wiki: "Night of the Long Knives" },
  { slug: "nuremberg-laws", name: "The Nuremberg Laws", period: "world-wars", civ: "nazi-germany", year: 1935, wiki: "Nuremberg Laws" },
  { slug: "rhineland-remilitarized", name: "Remilitarization of the Rhineland", period: "world-wars", civ: "nazi-germany", year: 1936, wiki: "Remilitarization of the Rhineland" },
  { slug: "spanish-civil-war", name: "Spanish Civil War", period: "world-wars", year: 1936, endYear: 1939, wiki: "Spanish Civil War" },
  { slug: "bombing-of-guernica", name: "Bombing of Guernica", period: "world-wars", year: 1937, wiki: "Bombing of Guernica" },
  { slug: "anschluss", name: "The Anschluss", period: "world-wars", civ: "nazi-germany", year: 1938, wiki: "Anschluss" },
  { slug: "munich-agreement", name: "The Munich Agreement", period: "world-wars", civ: "nazi-germany", year: 1938, wiki: "Munich Agreement" },
  { slug: "kristallnacht", name: "Kristallnacht", period: "world-wars", civ: "nazi-germany", year: 1938, wiki: "Kristallnacht" },
  { slug: "molotov-ribbentrop", name: "Molotov–Ribbentrop Pact", period: "world-wars", civ: "nazi-germany", year: 1939, wiki: "Molotov–Ribbentrop Pact" },
  { slug: "invasion-of-poland", name: "Invasion of Poland", period: "world-wars", civ: "nazi-germany", year: 1939, wiki: "Invasion of Poland" },
  { slug: "winter-war", name: "The Winter War", period: "world-wars", civ: "soviet-union", year: 1939, endYear: 1940, wiki: "Winter War" },
  { slug: "fall-of-france", name: "The Fall of France", period: "world-wars", civ: "nazi-germany", year: 1940, wiki: "Battle of France" },
  { slug: "dunkirk-evacuation", name: "The Dunkirk Evacuation", period: "world-wars", year: 1940, wiki: "Dunkirk evacuation" },
  { slug: "battle-of-britain", name: "Battle of Britain", period: "world-wars", year: 1940, wiki: "Battle of Britain" },
  { slug: "the-blitz", name: "The Blitz", period: "world-wars", year: 1940, endYear: 1941, wiki: "The Blitz" },
  { slug: "operation-barbarossa", name: "Operation Barbarossa", period: "world-wars", civ: "nazi-germany", year: 1941, wiki: "Operation Barbarossa" },
  { slug: "siege-of-leningrad", name: "Siege of Leningrad", period: "world-wars", civ: "soviet-union", year: 1941, endYear: 1944, wiki: "Siege of Leningrad" },
  { slug: "the-holocaust", name: "The Holocaust", period: "world-wars", civ: "nazi-germany", year: 1941, endYear: 1945, wiki: "The Holocaust" },
  { slug: "wannsee-conference", name: "The Wannsee Conference", period: "world-wars", civ: "nazi-germany", year: 1942, wiki: "Wannsee Conference" },
  { slug: "battle-of-stalingrad", name: "Battle of Stalingrad", period: "world-wars", civ: "soviet-union", year: 1942, endYear: 1943, wiki: "Battle of Stalingrad" },
  { slug: "battle-of-kursk", name: "Battle of Kursk", period: "world-wars", civ: "soviet-union", year: 1943, wiki: "Battle of Kursk" },
  { slug: "allied-invasion-of-italy", name: "Allied Invasion of Italy", period: "world-wars", civ: "fascist-italy", year: 1943, wiki: "Allied invasion of Italy" },
  { slug: "normandy-landings", name: "D-Day: The Normandy Landings", period: "world-wars", year: 1944, wiki: "Normandy landings" },
  { slug: "warsaw-uprising", name: "The Warsaw Uprising", period: "world-wars", year: 1944, wiki: "Warsaw Uprising" },
  { slug: "battle-of-the-bulge", name: "Battle of the Bulge", period: "world-wars", year: 1944, endYear: 1945, wiki: "Battle of the Bulge" },
  { slug: "yalta-conference", name: "The Yalta Conference", period: "world-wars", year: 1945, wiki: "Yalta Conference" },
  { slug: "bombing-of-dresden", name: "Bombing of Dresden", period: "world-wars", year: 1945, wiki: "Bombing of Dresden" },
  { slug: "ve-day", name: "Victory in Europe Day", period: "world-wars", year: 1945, wiki: "Victory in Europe Day" },
  { slug: "potsdam-conference", name: "The Potsdam Conference", period: "world-wars", year: 1945, wiki: "Potsdam Conference" },

  // ───────────── The Cold War ─────────────
  { slug: "nuremberg-trials", name: "The Nuremberg Trials", period: "cold-war", year: 1945, endYear: 1946, wiki: "Nuremberg trials" },
  { slug: "iron-curtain", name: "The Iron Curtain Descends", period: "cold-war", year: 1946, wiki: "Iron Curtain" },
  { slug: "truman-doctrine", name: "The Truman Doctrine", period: "cold-war", year: 1947, wiki: "Truman Doctrine" },
  { slug: "marshall-plan", name: "The Marshall Plan", period: "cold-war", year: 1948, wiki: "Marshall Plan" },
  { slug: "czechoslovak-coup", name: "Communist Coup in Czechoslovakia", period: "cold-war", year: 1948, wiki: "1948 Czechoslovak coup d'état" },
  { slug: "berlin-blockade", name: "Berlin Blockade & Airlift", period: "cold-war", year: 1948, endYear: 1949, wiki: "Berlin Blockade" },
  { slug: "founding-of-nato", name: "Founding of NATO", period: "cold-war", civ: "nato", year: 1949, wiki: "NATO" },
  { slug: "council-of-europe", name: "Founding of the Council of Europe", period: "cold-war", year: 1949, wiki: "Council of Europe" },
  { slug: "soviet-atomic-bomb", name: "The Soviet Atomic Bomb", period: "cold-war", civ: "soviet-union", year: 1949, wiki: "RDS-1" },
  { slug: "schuman-declaration", name: "The Schuman Declaration", period: "cold-war", year: 1950, wiki: "Schuman Declaration" },
  { slug: "coal-and-steel-community", name: "European Coal & Steel Community", period: "cold-war", year: 1951, wiki: "European Coal and Steel Community" },
  { slug: "death-of-stalin", name: "Death of Stalin", period: "cold-war", civ: "soviet-union", year: 1953, wiki: "Death and state funeral of Joseph Stalin" },
  { slug: "east-german-uprising", name: "East German Uprising", period: "cold-war", civ: "east-germany", year: 1953, wiki: "East German uprising of 1953" },
  { slug: "warsaw-pact-founded", name: "The Warsaw Pact Founded", period: "cold-war", civ: "warsaw-pact", year: 1955, wiki: "Warsaw Pact" },
  { slug: "secret-speech", name: "Khrushchev's Secret Speech", period: "cold-war", civ: "soviet-union", year: 1956, wiki: "On the Cult of Personality and Its Consequences" },
  { slug: "hungarian-revolution", name: "Hungarian Revolution of 1956", period: "cold-war", civ: "warsaw-pact", year: 1956, wiki: "Hungarian Revolution of 1956" },
  { slug: "suez-crisis", name: "The Suez Crisis", period: "cold-war", year: 1956, wiki: "Suez Crisis" },
  { slug: "treaty-of-rome", name: "Treaty of Rome", period: "cold-war", year: 1957, wiki: "Treaty of Rome" },
  { slug: "sputnik", name: "Sputnik Opens the Space Age", period: "cold-war", civ: "soviet-union", year: 1957, wiki: "Sputnik 1" },
  { slug: "first-human-in-space", name: "Gagarin — First Human in Space", period: "cold-war", civ: "soviet-union", year: 1961, wiki: "Yuri Gagarin" },
  { slug: "berlin-wall", name: "The Berlin Wall Rises", period: "cold-war", civ: "east-germany", year: 1961, wiki: "Berlin Wall" },
  { slug: "cuban-missile-crisis", name: "The Cuban Missile Crisis", period: "cold-war", civ: "soviet-union", year: 1962, wiki: "Cuban Missile Crisis" },
  { slug: "may-68", name: "May 68 in France", period: "cold-war", year: 1968, wiki: "May 68" },
  { slug: "prague-spring", name: "The Prague Spring", period: "cold-war", civ: "warsaw-pact", year: 1968, wiki: "Prague Spring" },
  { slug: "ostpolitik", name: "Brandt's Ostpolitik", period: "cold-war", civ: "west-germany", year: 1969, endYear: 1974, wiki: "Ostpolitik" },
  { slug: "carnation-revolution", name: "The Carnation Revolution", period: "cold-war", year: 1974, wiki: "Carnation Revolution" },
  { slug: "helsinki-accords", name: "Helsinki Accords", period: "cold-war", year: 1975, wiki: "Helsinki Accords" },
  { slug: "spanish-transition", name: "Spain's Transition to Democracy", period: "cold-war", year: 1975, endYear: 1982, wiki: "Spanish transition to democracy" },
  { slug: "solidarity-movement", name: "Solidarity Movement", period: "cold-war", civ: "warsaw-pact", year: 1980, wiki: "Solidarity (Polish trade union)" },
  { slug: "martial-law-poland", name: "Martial Law in Poland", period: "cold-war", civ: "warsaw-pact", year: 1981, wiki: "Martial law in Poland" },
  { slug: "perestroika", name: "Perestroika & Glasnost", period: "cold-war", civ: "soviet-union", year: 1985, wiki: "Perestroika" },
  { slug: "chernobyl-disaster", name: "The Chernobyl Disaster", period: "cold-war", civ: "soviet-union", year: 1986, wiki: "Chernobyl disaster" },
  { slug: "pan-european-picnic", name: "The Pan-European Picnic", period: "cold-war", year: 1989, wiki: "Pan-European Picnic" },
  { slug: "fall-of-berlin-wall", name: "Fall of the Berlin Wall", period: "cold-war", civ: "east-germany", year: 1989, wiki: "Fall of the Berlin Wall" },
  { slug: "velvet-revolution", name: "The Velvet Revolution", period: "cold-war", year: 1989, wiki: "Velvet Revolution" },
  { slug: "romanian-revolution", name: "The Romanian Revolution", period: "cold-war", year: 1989, wiki: "Romanian revolution" },
  { slug: "german-reunification", name: "German Reunification", period: "cold-war", civ: "west-germany", year: 1990, wiki: "German reunification" },
  { slug: "dissolution-of-ussr", name: "Dissolution of the Soviet Union", period: "cold-war", civ: "soviet-union", year: 1991, wiki: "Dissolution of the Soviet Union" },

  // ───────────── Contemporary Europe ─────────────
  { slug: "yugoslav-wars", name: "The Yugoslav Wars", period: "contemporary-europe", year: 1991, endYear: 2001, wiki: "Yugoslav Wars" },
  { slug: "maastricht-treaty", name: "Maastricht Treaty", period: "contemporary-europe", civ: "european-union", year: 1992, wiki: "Maastricht Treaty" },
  { slug: "velvet-divorce", name: "The Velvet Divorce", period: "contemporary-europe", year: 1993, wiki: "Dissolution of Czechoslovakia" },
  { slug: "channel-tunnel", name: "The Channel Tunnel Opens", period: "contemporary-europe", year: 1994, wiki: "Channel Tunnel" },
  { slug: "eu-enlargement-1995", name: "1995 EU Enlargement", period: "contemporary-europe", civ: "european-union", year: 1995, wiki: "1995 enlargement of the European Union" },
  { slug: "srebrenica-massacre", name: "The Srebrenica Massacre", period: "contemporary-europe", year: 1995, wiki: "Srebrenica massacre" },
  { slug: "dayton-agreement", name: "The Dayton Agreement", period: "contemporary-europe", year: 1995, wiki: "Dayton Agreement" },
  { slug: "good-friday-agreement", name: "Good Friday Agreement", period: "contemporary-europe", year: 1998, wiki: "Good Friday Agreement" },
  { slug: "kosovo-war", name: "The Kosovo War", period: "contemporary-europe", year: 1998, endYear: 1999, wiki: "Kosovo War" },
  { slug: "introduction-of-euro", name: "Introduction of the Euro", period: "contemporary-europe", civ: "european-union", year: 1999, wiki: "Euro" },
  { slug: "eu-enlargement-2004", name: "2004 EU Enlargement", period: "contemporary-europe", civ: "european-union", year: 2004, wiki: "2004 enlargement of the European Union" },
  { slug: "madrid-bombings", name: "Madrid Train Bombings", period: "contemporary-europe", year: 2004, wiki: "2004 Madrid train bombings" },
  { slug: "london-bombings", name: "7/7 London Bombings", period: "contemporary-europe", year: 2005, wiki: "7 July 2005 London bombings" },
  { slug: "treaty-of-lisbon", name: "Treaty of Lisbon", period: "contemporary-europe", civ: "european-union", year: 2007, wiki: "Treaty of Lisbon" },
  { slug: "great-recession", name: "The Great Recession", period: "contemporary-europe", year: 2008, wiki: "Great Recession" },
  { slug: "european-debt-crisis", name: "European Debt Crisis", period: "contemporary-europe", civ: "european-union", year: 2009, endYear: 2014, wiki: "European debt crisis" },
  { slug: "annexation-of-crimea", name: "Annexation of Crimea", period: "contemporary-europe", civ: "russia", year: 2014, wiki: "Annexation of Crimea by the Russian Federation" },
  { slug: "migrant-crisis", name: "The European Migrant Crisis", period: "contemporary-europe", year: 2015, wiki: "2015 European migrant crisis" },
  { slug: "paris-attacks", name: "November 2015 Paris Attacks", period: "contemporary-europe", year: 2015, wiki: "November 2015 Paris attacks" },
  { slug: "brexit", name: "Brexit", period: "contemporary-europe", year: 2016, endYear: 2020, wiki: "Brexit" },
  { slug: "covid-in-europe", name: "COVID-19 Pandemic in Europe", period: "contemporary-europe", year: 2020, endYear: 2023, wiki: "COVID-19 pandemic in Europe" },
  { slug: "invasion-of-ukraine", name: "Russian Invasion of Ukraine", period: "contemporary-europe", civ: "russia", year: 2022, wiki: "Russian invasion of Ukraine" },
  { slug: "nordic-nato-accession", name: "Finland & Sweden Join NATO", period: "contemporary-europe", civ: "nato", year: 2023, endYear: 2024, wiki: "Enlargement of NATO" },

  // ───────────── beyond Europe: the causal spine (chain nodes, off-frieze) ─────────────
  { slug: "pompey-jerusalem", name: "Pompey Takes Jerusalem", period: "ancient-europe", year: -63, wiki: "Siege of Jerusalem (63 BC)", onTimeline: false },
  { slug: "roman-judea", name: "Rome Annexes Judaea", period: "ancient-europe", year: 6, wiki: "Judaea (Roman province)", onTimeline: false },
  { slug: "jewish-roman-wars", name: "The Jewish–Roman Wars", period: "ancient-europe", year: 66, endYear: 135, wiki: "Jewish–Roman wars", onTimeline: false },
  { slug: "siege-of-jerusalem-70", name: "Destruction of the Second Temple", period: "ancient-europe", year: 70, wiki: "Siege of Jerusalem (70 CE)", onTimeline: false },
  { slug: "rise-of-islam", name: "The Rise of Islam", period: "middle-ages", year: 610, endYear: 632, wiki: "Muhammad", onTimeline: false },
  { slug: "early-muslim-conquests", name: "The Early Muslim Conquests", period: "middle-ages", year: 622, endYear: 750, wiki: "Early Muslim conquests", onTimeline: false },
  { slug: "muslim-conquest-levant", name: "Muslim Conquest of the Levant", period: "middle-ages", year: 634, endYear: 638, wiki: "Muslim conquest of the Levant", onTimeline: false },
  { slug: "alhambra-decree", name: "Expulsion of the Jews from Spain", period: "age-of-exploration", year: 1492, wiki: "Alhambra Decree", onTimeline: false },
  { slug: "ottoman-mamluk-war", name: "Ottomans Take the Arab Lands", period: "reformation", year: 1516, endYear: 1517, wiki: "Ottoman–Mamluk War (1516–1517)", onTimeline: false },
  { slug: "american-revolution", name: "The American Revolution", period: "enlightenment", year: 1775, endYear: 1783, wiki: "American Revolution", onTimeline: false },
  { slug: "pogroms-russian-empire", name: "Pogroms in the Russian Empire", period: "age-of-imperialism", year: 1881, endYear: 1921, wiki: "Anti-Jewish pogroms in the Russian Empire", onTimeline: false },
  { slug: "first-zionist-congress", name: "First Zionist Congress", period: "age-of-imperialism", year: 1897, wiki: "First Zionist Congress", onTimeline: false },
  { slug: "young-turk-revolution", name: "Young Turk Revolution", period: "age-of-imperialism", year: 1908, wiki: "Young Turk Revolution", onTimeline: false },
  { slug: "anglo-persian-oil", name: "Oil Struck in Persia", period: "age-of-imperialism", year: 1908, wiki: "Anglo-Persian Oil Company", onTimeline: false },
  { slug: "armenian-genocide", name: "The Armenian Genocide", period: "world-wars", year: 1915, endYear: 1917, wiki: "Armenian genocide", onTimeline: false },
  { slug: "sykes-picot", name: "Sykes–Picot Agreement", period: "world-wars", year: 1916, wiki: "Sykes–Picot Agreement", onTimeline: false },
  { slug: "arab-revolt", name: "The Arab Revolt", period: "world-wars", year: 1916, endYear: 1918, wiki: "Arab Revolt", onTimeline: false },
  { slug: "balfour-declaration", name: "The Balfour Declaration", period: "world-wars", year: 1917, wiki: "Balfour Declaration", onTimeline: false },
  { slug: "partition-of-ottoman-empire", name: "Partition of the Ottoman Empire", period: "world-wars", year: 1918, endYear: 1922, wiki: "Partition of the Ottoman Empire", onTimeline: false },
  { slug: "mandatory-palestine", name: "Mandatory Palestine", period: "world-wars", year: 1920, endYear: 1948, wiki: "Mandatory Palestine", onTimeline: false },
  { slug: "attack-pearl-harbor", name: "Attack on Pearl Harbor", period: "world-wars", year: 1941, wiki: "Attack on Pearl Harbor", onTimeline: false },
  { slug: "decolonisation", name: "Decolonisation", period: "cold-war", year: 1945, endYear: 1975, wiki: "Decolonization", onTimeline: false },
  { slug: "un-partition-palestine", name: "UN Partition Plan for Palestine", period: "cold-war", year: 1947, wiki: "United Nations Partition Plan for Palestine", onTimeline: false },
  { slug: "israeli-independence", name: "Founding of the State of Israel", period: "cold-war", year: 1948, wiki: "Israeli Declaration of Independence", onTimeline: false },
  { slug: "nakba", name: "The Nakba", period: "cold-war", year: 1948, wiki: "Nakba", onTimeline: false },
  { slug: "arab-israeli-war-1948", name: "First Arab–Israeli War", period: "cold-war", year: 1948, endYear: 1949, wiki: "1948 Arab–Israeli War", onTimeline: false },
  { slug: "iran-coup-1953", name: "Anglo-American Coup in Iran", period: "cold-war", year: 1953, wiki: "1953 Iranian coup d'état", onTimeline: false },
  { slug: "baath-coup-syria", name: "Ba'athist Coup in Syria", period: "cold-war", year: 1963, wiki: "1963 Syrian coup d'état", onTimeline: false },
  { slug: "six-day-war", name: "The Six-Day War", period: "cold-war", year: 1967, wiki: "Six-Day War", onTimeline: false },
  { slug: "assad-takeover", name: "Assad Seizes Power in Syria", period: "cold-war", year: 1970, wiki: "1970 Syrian coup d'état", onTimeline: false },
  { slug: "yom-kippur-war", name: "The Yom Kippur War", period: "cold-war", year: 1973, wiki: "Yom Kippur War", onTimeline: false },
  { slug: "oil-crisis-1973", name: "The 1973 Oil Shock", period: "cold-war", year: 1973, wiki: "1973 oil crisis", onTimeline: false },
  { slug: "lebanese-civil-war", name: "Lebanese Civil War", period: "cold-war", year: 1975, endYear: 1990, wiki: "Lebanese Civil War", onTimeline: false },
  { slug: "camp-david-accords", name: "Camp David Accords", period: "cold-war", year: 1978, wiki: "Camp David Accords", onTimeline: false },
  { slug: "iranian-revolution", name: "The Iranian Revolution", period: "cold-war", year: 1979, wiki: "Iranian Revolution", onTimeline: false },
  { slug: "soviet-afghan-war", name: "The Soviet–Afghan War", period: "cold-war", year: 1979, endYear: 1989, wiki: "Soviet–Afghan War", onTimeline: false },
  { slug: "iran-iraq-war", name: "The Iran–Iraq War", period: "cold-war", year: 1980, endYear: 1988, wiki: "Iran–Iraq War", onTimeline: false },
  { slug: "hama-massacre", name: "The Hama Massacre", period: "cold-war", year: 1982, wiki: "1982 Hama massacre", onTimeline: false },
  { slug: "gulf-war", name: "The Gulf War", period: "cold-war", year: 1990, endYear: 1991, wiki: "Gulf War", onTimeline: false },
  { slug: "september-11", name: "September 11 Attacks", period: "contemporary-europe", year: 2001, wiki: "September 11 attacks", onTimeline: false },
  { slug: "war-afghanistan-2001", name: "War in Afghanistan", period: "contemporary-europe", year: 2001, endYear: 2021, wiki: "War in Afghanistan (2001–2021)", onTimeline: false },
  { slug: "iraq-war", name: "The Iraq War", period: "contemporary-europe", year: 2003, endYear: 2011, wiki: "Iraq War", onTimeline: false },
  { slug: "arab-spring", name: "The Arab Spring", period: "contemporary-europe", year: 2010, endYear: 2012, wiki: "Arab Spring", onTimeline: false },
  { slug: "syrian-civil-war", name: "The Syrian Civil War", period: "contemporary-europe", year: 2011, wiki: "Syrian civil war", onTimeline: false },
  { slug: "islamic-state", name: "Rise of the Islamic State", period: "contemporary-europe", year: 2013, endYear: 2019, wiki: "Islamic State", onTimeline: false },
];
